apiVersion: v1
kind: Service
metadata:
  name: {{ include "wyd-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wyd-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "wyd-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
